### PR TITLE
Add event info to payloads of webhook service

### LINKED ISSUE #481: Webhook: Include the event type inside the event payload

### PR DESCRIPTION
**Pull request by altafan**
This closes #481.

Please @tiero review this.

### CODE REVIEW

**Review by tiero — COMMENTED** [review]
what about other topics, account low balance and withdraw @altafan

**Comment by altafan** [comment]
i've added the event to the payloads of all types of topic @tiero.

**Comment by tiero** [comment]
ah ok wait, before trade settled was in blockshain listner, was missing the function

**Comment by altafan** [comment]
yeah, i added the util function just like did for other topics.. better to read like this.

**Pull request merged**
