### PR TITLE
Refactor serveMux

### LINKED ISSUE #415: Refactor multiplexing to make it work with reverse proxy such as Caddy
Ref: https://github.com/caddyserver/caddy/issues/3997

This way we could serve behind caddy server reverse proxy and automatic TLS management easily

Code can be taken from here https://github.com/tiero/zion/blob/serverless/cmd/zion/main.go#L95

### LINKED ISSUE #418: TLS: Specify all the cipher suite in sane order
Like this commit https://github.com/tdex-network/tor-proxy/commit/871d014533fa1453b0d10ce30396bff8fd8c14f0

### PR DESCRIPTION
**Pull request by altafan**
This updates the creation of the multiplexer with grpc server, http2 grpc-web server and http1 grpc-web server.

This also fixes the signing algorithms supported in TLS configuration.

This closes #415.
This closes #418.

Please @tiero review this.

### CODE REVIEW

**Comment by tiero** [comment]
did you tried with a reverse proxy?

ie. 

- Compose 

```yml
version: "3.7"

services:
  tdexd:
    ....
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy_data:/data
```

- Caddyfile

```Caddyfile
:80

reverse_proxy tdex:8080
```

**Comment by altafan** [comment]
@tiero I made a test locally and while I have no problems reaching the daemon at `localhost:9000`, I have this error if I try to contact caddy at `localhost:8080` (I tweaked the config and the compose files accordingly):

```
[tdex] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
```

**Comment by tiero** [comment]
> @tiero I made a test locally and while I have no problems reaching the daemon at `localhost:9000`, I have this error if I try to contact caddy at `localhost:8080` (I tweaked the config and the compose files accordingly):
> 
> ```
> [tdex] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
> ```

reverse proxy should go on the un-auth trade interface AFAIK, here you are proxying the operator one with macaroon/TLS auth right?

**Comment by altafan** [comment]
> reverse proxy should go on the un-auth trade interface AFAIK, here you are proxying the operator one with macaroon/TLS auth right?

Yes, I'm trying to proxy to the auth Operator interface. I'm gonna try it with mac/TLS disabled.

**Comment by tiero** [comment]
To proxy TLS trnasport I think extra tweaking is necessary 

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#transport

**Pull request merged**
