### PR TITLE
[Docker] Add integration testing for the docker container

### PR DESCRIPTION
**Pull request by louisinger**
**This PR adds a `cli_test.go` file in `cmd/tdex` which runs a set of cli commands inside tdexd containers**

TL;DR
- Add a new process in MakeFile: `containertest`
- Add CLI tests in `cli_test.go`: test for init and unlock the wallet + create, list and open a market

_I don't test all the methods because it could be a bit overkill in my opinion: we already test all of the CLI methods in others tests files. Please tell me if it is a good decision._

PS: Note that multiple tdexd containers are resistant to race errors --> could be the solution at the [former badger concurrency issue](https://github.com/TDex-network/tdex-daemon/issues/193). 

@sekulicd @tiero @altafan please review

### CODE REVIEW

**Comment by altafan** [comment]
Guys, sorry for this soo late reply, but don't know why, i'm not able to follow this discussion from my laptop.. always getting a 500 error.
Not ideal to continue this from mobile, but however 😅...

With my latest PR, basically I tried to follow the first 3 points of the list given by dusan, which I essentially agree with.

It would be interesting to know if, using test suits, it would be possible to have isolated envs such that every suit could be ran into a t.Run block.

Running unit tests within t.Run blocks would be nice to speed up their execution. But since some of them, in particular those of the app layer, make use of mocked env vars this is currently not achievable because cause of race condition.

**Comment by altafan** [comment]
One thing that i want to add to complete point 5 is that every state should be statically generated with a yml (also json file could be an option).

At the moment, there are mocks that are created "dynamically", in the sense they are based on hardcoded data that are used to create the actual mocks. Sometimes this is accomplished by using the same service that should be tested! It's fucking terrible trying to share a link from mobile, but take a look at how the trades are mocked in the app layer tests (test_util.go).

Ideally, instead, every unit test should start with a mocked state read from yml, json or whatever, execute a function, check the output and eventually destroy the state.

**Comment by tiero** [comment]
I agree with @sekulicd

I would suggest to read also this post regarding testing https://threedots.tech/post/microservices-test-architecture and try to re-thing testing architecture from ground up

**Comment by tiero** [comment]
Closing this in favor of #301

**Pull request closed without merging**
